#pragma config(Motor,  port2,           backLeft,      tmotorNone, openLoop)
#pragma config(Motor,  port3,           leftClaw,      tmotorNone, openLoop)
#pragma config(Motor,  port4,           middleLeft,    tmotorNone, openLoop)
#pragma config(Motor,  port5,           leftDRFBY,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#pragma platform(VEX2)
#include "Vex_Competition_Includes.c"
#include "driving.c"
void pre_auton(){

}
void auton(){

}
task main(){

}
