#pragma config(Sensor, dgtl4,  encoder,        sensorNone)
#pragma config(Sensor, dgtl7,  encoder4,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  encoder5,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoder6,       sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		motor[port1]=vexRT[Ch2];
		motor[port2]=vexRT[Ch2];
		motor[port3]=vexRT[Ch2];
		motor[port4]=vexRT[Ch2];
		motor[port5]=vexRT[Ch2];
		motor[port6]=vexRT[Ch2];
		motor[port7]=vexRT[Ch2];
		motor[port8]=vexRT[Ch2];
		motor[port9]=vexRT[Ch2];
		motor[port10]=vexRT[Ch2];
	}
}
