#pragma config(Sensor, in1,    fourbarPot,     sensorPotentiometer)
#pragma config(Sensor, in2,    gyro1,          sensorAnalog)
#pragma config(Sensor, dgtl1,  ldtEnc,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  data,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  clock,          sensorDigitalOut)
#pragma config(Sensor, dgtl5,  ldr4bEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rdr4bEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rdtEnc,         sensorQuadEncoder)
#pragma config(Sensor, dgtl11, sound,          sensorSONAR_mm)
#pragma config(Motor,  port1,           mgm,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ldt1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ldr4b,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port4,           fourbar,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rdt1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ldt2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rdr4b,         tmotorVex393_MC29, PIDControl, encoderPort, dgtl7)
#pragma config(Motor,  port9,           rdt2,          tmotorVex393_MC29, openLoop)
#pragma config(MotorPidSetting,  port3,  25, 100, 1000, 2, 10,   100, 0, 40)
#pragma config(MotorPidSetting,  port8,  25, 100, 1000, 2, 10,   100, 0, 40)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Globals")
#pragma DebuggerWindows("Locals")
#pragma DebuggerWindows("Sensors")
#pragma DebuggerWindows("VexLCD")
#pragma DebuggerWindows("taskStatus")
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#pragma platform(VEX2)
#include "Vex_Competition_Includes.c"
#include "driving.c"

void waitForRelease()
{
	while(nLCDButtons != 0)
		wait1Msec(5);
}
void waitForPress()
{
	while(nLCDButtons == 0)
		wait1Msec(5);
}
bool autonSelected = false;
void pre_auton(){//Selects auton program
	bStopTasksBetweenModes = false;
	delay(1100);
	GyroInit(in2);
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	playTone(440,10);
	wait1Msec(100);
	playTone(660,10);
	setStripColor(120,31,255,255,255);
	while((nLCDButtons != centerButton) && !autonSelected){
		switch(lcdCount){
		case 0:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, zerothAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,0,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount = 18;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
		break;
		case 1:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, firstAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,127,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 2:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, secondAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,255,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 3:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, thirdAutonString);
			displayEnterString(1);
			setStripColor(120,31,127,255,0);
			waitForPress();
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 4:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, fourthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,255,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 5:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, fifthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,0,255);
			setStripColor(120,31,0,255,127);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 6:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, sixthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,255,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 7:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, seventhAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,127,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 8:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, eighthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,0,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 9:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, ninthAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,127,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 10:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, tenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,255,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 11:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, eleventhAutonString);
			displayEnterString(1);
			setStripColor(120,31,127,255,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 12:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, twelfthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,255,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 13:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, thirteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,255,127);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 14:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, fourteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,255,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 15:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, fifteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,127,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 16:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, sixteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,0,0,255);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 17:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, seventeenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,0,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount++;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 18:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, eighteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,0,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount=0;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		case 19:
			clearLCDLine(0);
			clearLCDLine(1);
			displayLCDString(0,0, nineteenthAutonString);
			displayEnterString(1);
			setStripColor(120,31,255,0,0);
			waitForPress();
			if(nLCDButtons == leftButton){
				waitForRelease();
				lcdCount--;
			}
			else if(nLCDButtons == rightButton){
				waitForRelease();
				lcdCount=0;
			}
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		default:
			lcdCount = 0;
			SensorValue[rdr4bEnc]=0;
			SensorValue[ldr4bEnc]=0;
			SensorValue[ldtEnc]=0;
			SensorValue[rdtEnc]=0;
			break;
		}
		SensorValue[ldtEnc]=0;
		SensorValue[rdtEnc]=0;
	}
	autonSelected = true;
}
task autonomous(){
	startTask(auton);
}
task usercontrol(){
	startTask(fadeColors);
	startTask(drive);
}
