#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          frontRight,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	int c2 = 0, c3 = 0;
	while(true){
		const int THRESHOLD = 20;
		if(abs(vexRT[Ch2])>THRESHOLD)
			c2 = vexRT[Ch2];
		else
			c2 = 0;
		if(abs(vexRT[Ch3])>THRESHOLD)
			c3 = vexRT[Ch3];
		else
			c3 = 0;
		motor[backLeft] = motor[frontLeft] = c3;
		motor[backRight] = motor[frontRight] = c2;
	}
}
