#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Vex_Competition_Includes.c"
void main(){
	while(true){
		motor[backLeft] = motor[backRight] = vexRT[Ch3];
		motor[frontLeft] = motor[frontRight] = vexRT[Ch2];
	}
}
